default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: personal_development
  username: postgres
  password: "1234567890"

test:
  <<: *default
  database: personal_test
  username: postgres
  password: "1234567890"

production:
  <<: *default
  database: personal_production
  username: postgres
  password: "1234567890"
